# Copyright (c) 2026 ID8 Engineering AB
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: id8
      url-base: https://github.com/id8-engineering

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v3.2.1
      import: true

    - name: seven-board
      remote: id8
      repo-path: seven-board
      revision: main
      path: modules/seven-board

    - name: mender-mcu
      url: https://github.com/mendersoftware/mender-mcu
      revision: cf31fa22bf358a1c58b0c32a4337571a35e1a1fd
      path: modules/mender-mcu
