# Logging
CONFIG_LOG=y
CONFIG_HEAP_MEM_POOL_SIZE=16384

# ADC
CONFIG_ADC=y
# PWM
CONFIG_PWM=y

# Display
CONFIG_I2C=y
CONFIG_DISPLAY=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_CHARACTER_FRAMEBUFFER_USE_DEFAULT_FONTS=y
CONFIG_SSD1306=y

# LED
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_SPI=y
