# If RTT is enabled in MCUboot, J-Link can attach to MCUboot's RTT control block
# and app RTT logs may not appear after MCUboot jumps to the application.
CONFIG_LOG=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n
CONFIG_LOG_BACKEND_RTT=n

