name: Build

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build samples
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 #v6.0.2
        with:
          path: seven-firmware-samples
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 #v6.3.0
        with:
          python-version: 3.12

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@5ec39f5cba83346d83a836dfed1524270c660e28 #v1.0.14
        with:
          app-path: seven-firmware-samples
          toolchains: arm-zephyr-eabi
          ccache-cache-key: ubuntu-22.04

      - name: Build firmware
        working-directory: seven-firmware-samples
        shell: bash
        run: |
          make sample-all
