name: Conventional Commits

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: webiny/action-conventional-commits@1dc97face8fcf4db15ad186d34a1e44fdc5f0eb3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
